version: ~> 1.0

sudo: false
language: scala

services:
  - docker

scala:
  - 2.12.8

jdk:
  - openjdk11

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
 
before_script:
  - project/travis-before-build.sh

script:
  - sbt ++$TRAVIS_SCALA_VERSION headerCheck
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION test:compile
  - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite
  - sbt ++$TRAVIS_SCALA_VERSION test

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "Banno/kafka4s" && sbt ++$TRAVIS_SCALA_VERSION publish
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "Banno/kafka4s" && test $TRAVIS_SCALA_VERSION == "2.12.8" && sbt docs/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
    - $HOME/.rvm/
    - vendor/bundle

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete

