version: ~> 1.0

language: scala

dist: xenial

services:
  - docker

scala:
  - 2.12.11
  - 2.13.1

jdk:
  - openjdk8
  - openjdk11

before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
 
before_script:
  - project/travis-before-build.sh

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION headerCheck
  - sbt ++$TRAVIS_SCALA_VERSION "scalafmtSbtCheck;scalafmtCheckAll"
  - sbt ++2.12.11 docs/makeMicrosite
  - sbt ++2.12.11 test

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && (test $TRAVIS_BRANCH == "master" || test $TRAVIS_TAG != "") && test $TRAVIS_REPO_SLUG == "Banno/kafka4s" && sbt ++$TRAVIS_SCALA_VERSION ci-release
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "Banno/kafka4s" && sbt ++2.12.11 docs/publishMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt
    - $HOME/.rvm/
    - vendor/bundle

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete

